server:
  port: 3085
  https:
    cert:
    key:
  corsorigins:
  edition: local-ce:dev
  disableusage: false
  loopinterval: 5
  timeout: 120
  debug: true
etcd:
  host: etcd
  port: 2379
  timeout: 10
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: pipeline
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
cache:
  redis:
    redisoptions:
      addr: redis:6379
temporal:
  clientoptions:
    hostport: temporal:7233
tritonserver:
  host: triton-server
  grpcuri: triton-server:8001
  modelstore: /model-repository
connectorbackend:
  host: connector-backend
  publicport: 8082
  privateport: 3082
  https:
    cert:
    key:
modelbackend:
  host: model-backend
  publicport: 8083
  privateport: 3083
  https:
    cert:
    key:
pipelinebackend:
  host: pipeline-backend
  publicport: 8081
  privateport: 3081
  https:
    cert:
    key:
mgmtbackend:
  host: mgmt-backend
  publicport: 8084
  privateport: 3084
  https:
    cert:
    key:
usageserver:
  tlsenabled: true
  host: usage.instill.tech
  port: 443
